### ISSUE TITLE
Epic: Swagger 2.0 support

### ISSUE THREAD

**Issue by dnephin** [striglia/pyramid_swagger#94]
I thought I'd create this ticket as a tracking ticket for all the swagger 2.0 work.

**Important**:
All version compatibility logic (`if v1.2 do x, else do y`) should  be kept to a single module instead of cluttering the whole project with these switches.  Right now `pyramid_swagger` is well setup for this. All the logic switches can be kept to the `pyramid_swagger.ingest` module.

**Tasks**:
- [x] `pyramid_swagger.ingest.get_swagger_schema(...)` needs to be able to examine the schemas in the `schema_directory`, determine which swagger version it is, and return a `pyramid_swagger.model.SwaggerSchema` loaded with the swagger 2.0 schemas, but which conforms to the same interface as the swagger 1.2 schema.  (Interfaces changes for `api_declarations` addressed in #95)
- [x] api docs validation, should be handled by #81
- [x] `pyramid_swagger.tween.validation_tween_factory` should be largely unchanged, the validators it uses should support the same interface. Required changes are:
  * `cast_params()`  reads the schemas, so it may need an abstraction to work with both versions.
  * `validate_response()` needs to change because `void` doesn't appear to be a type any more
  * `handle_request` reads the body param name from the schema, but it could just be a constant
- [x] `pyramid_swagger.api.register_api_doc_endpoints()` will need to be changed to just return any file in the directory for 2.0. (based on #95)

I think the bulk of the work is really the first task. Once we have an interface that hides the differences between the specs it should be easy to integrate without adding any branches to handled the differences between spec versions.

**Comment by striglia** [comment]
Sounds pretty solid to me. As you say, the main work is transparently discovering and ingesting the 1.2 or 2.0 schema without explicit specifying. Bravado-core should solve both spec validation and at least providing the interface for request/response validation. At that point, for the purposes of validation pyramid_swagger just has to interface with bravado-core.

Ideally I'd like `register_api_doc_endpoints` to just accept the list of ingested schemas (which will contain their versions) rather than the current model of re-ingesting them. The re-ingest model seems a little dated at this point.

**Comment by analogue** [comment]
After having a good look at pyramid-swagger, I don't think this approach is viable.  I'll go through my initial list of road blocks:

1) "All the logic switches can be kept to the pyramid_swagger.ingest module."
Ingestion is not the only place 1.2 and 2.0 differ in logic. It is pervasive and far from easy to keep isolated.

2) Task 1: "determine which swagger version it is, and return a pyramid_swagger.model.SwaggerSchema loaded with the swagger 2.0 schemas, but which conforms to the same interface as the swagger 1.2 schema."

This is trying to fit the way 2.0 works into the same code path for 1.2 relying on the interfaces (what exactly are these interfaces?) to make things work.

3) Task 3: "pyramid_swagger.tween.validation_tween_factory should be largely unchanged, the validators it uses should support the same interface"

2.0 should not use any validators in pyramid swagger. It should use those available in bravado. Once 1.2 is deprecated, pyramid-swagger should have no validation logic.

I took a stab at the proposed changes I'd make in tween.py below. This assumes there is an immediate fork in the road for 1.2 vs 2.0 clients (1.2 requests continue as in the existing code, 2.0 requests have a completely new path). 

tween.py
=========
1)
```python
class Settings(namedtuple(
    'Settings',
    [
        'schema',   # bravado.mapping.spec.Spec replaces pyramid_swagger.model.SwaggerSchema
        'validate_request',
        'validate_response',
        'validate_path',
        'exclude_paths',
        'exclude_routes',
    ]
)):
```
2)
validation_tween_factory replaced by swagger_tween_factory.
request_data dict seems to be the interface for hand off from the
tween to bravado. validator_map not used anymore since bravado handles
validation.
```python
def swagger_tween_factory(handler, registry):
    """Pyramid tween for Swagger 2.0 based services.

    - validates request/response elements conform to a Swagger 2.0 Specifiication
    - marshals/unmarshals request/response schema objects to python models
    - transforms request/request primitive types to rich 'format' types
    """
    ...
    
	# hand off of request to bravado 
	request_data = handle_request(
		PyramidSwaggerRequest(request, route_info),
		validation_context)
		validator_map) 

	def swagger_data(_):
		return request_data

	# hand back of request to tween
	request.set_property(swagger_data)

	# view (or whatever) does its thing..
	response = handler(request)

	# hand response over to bravado - not just validation, transformation
	# and marshaling too
	with validation_context(request, response=response):
		handle_response(response, schema)
	
	# response (mutated as necessary) handed back to tween
	return response
```

3) Re-implement handle_request(..) to use bravado

```python
def handle_request(request, schema, validation_context):
    """Validate the request against the swagger spec and return a dict with
    all parameter values available in the request, casted to the expected
    python type.

    :param request: a :class:`PyramidSwaggerRequest` to validate
    :param schema: :class:`bravado.mapping.spec.Spec`
    :param validation_context: a context manager for wrapping validation
        errors
    :returns: a :class:`dict` of request data for each parameter in the swagger
        spec
    """
    request_data = {}
    op = get_operation_for(schema, request)  # new method to map request to operation
    for param in op.params:
		request_data[param.name] = bravado.mapping.param.unmarshal_param(param, request) 
    return request_data
```

4) Re-implmenent validate_response(...) to use bravado. Should probably
rename to handle_response(..) to match handle_request(...)
```python
def handle_response(response, schema):
    """Marshal response including validation and transformation.

    :param response: the response object to validate
    :type response: :class:`pyramid.response.Response`
    :type schema: :class:`bravado.mapping.spec.Spec`
    """
    response_spec = get_response_spec_for(response, schema)
    validate_response(response_spec, response)
    marshal_response(respnose_spec, response)
    ...
```

**Comment by dnephin** [comment]
> Ingestion is not the only place 1.2 and 2.0 differ in logic. It is pervasive and far from easy to keep isolated.

Do you have any examples of this. Really the only place that cares anything at all about the schema is ingestion (with the exception of the 3 places I've outlined). Everything should be fine behind the common validator interface.

Validation of the schemas also cares, but we already have that logic build into ssv, so it's really not an issue.

> This is trying to fit the way 2.0 works into the same code path for 1.2 relying on the interfaces (what exactly are these interfaces?) to make things work.

The point is that the interfaces are not 1.2 specific, they are specific to pyramid which is not changing.

The interface is `pyramid_swagger.model.SwaggerSchema`, which exposes validators (the jsonschema.validator interface), and a list of routes (with the changes in #95).  Neither of these interfaces are specific to swagger 1.2, and they allow the rest of the library to remain the same (which is good because it's well structured now).

> 2.0 should not use any validators in pyramid swagger. It should use those available in bravado. Once 1.2 is deprecated, pyramid-swagger should have no validation logic.

That's fine, the interface used by these validators should be identical. It should be the jsonschema interface of `Validator(schema).validate(instance)`.  Whatever objects are exposed through `SwaggerSchema.validators_for_request()` will be used.

> 1.2 requests continue as in the existing code, 2.0 requests have a completely new path

Even given your suggested edits this is hardly a completely new path, they're just swapping out one abstraction layer above what I think it should be.

We absolutely should be able to expose the validation using the same interface and the validation_mapping. The interface has nothing to do with swagger 1.2, it's exactly the right interface for what we need here. "Given a request and a validate, perform that validation".

I could see an argument for using something like the `Operation` from bravado-core, but **not** in it's current state.

As long as [`construct_request`]( https://github.com/Yelp/swagger-py/blob/swagger2.0/bravado/mapping/operation.py#L120), `construct_params()`, `__call__` (which actually performs a request) are method on operation, an operation object has **no place** in `pyramid_swagger`.

The `Resource` and `Operation` abstractions make a lot of sense in the client because of how requests are performed. In the server they don't really make sense at all. All you care about is "give me the validators for this request".  Resource

If bravado-core gets further refactored to split out client concerns from the validation and marshalling, I think it could work.

-------------

Another important point that isn't being called out explicitly here is that these changes completely break backwards compatibility for existing users of the library. Right now `pyramid_swagger` returns dicts. In fact until the latest rc release, it didn't even modify the request itself. This change would have it return model objects. I think that's a discussion that needs to be addressed.

So far I haven't seen any feature requests for models coming out of pyramid_swagger, and I don't think it's really necessary to force that on users just to get swagger 2.0 support. These concerns should be easy to separate.

**Comment by striglia** [comment]
Closing as completed
